swagger: "2.0"
info:
  version: "0.0.1"
  title: AGZ App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /user:
    # binds a127 app logic to a route
    x-swagger-router-controller: Signup
    post:
      description: 用户注册
      # used as the method name of the controller
      operationId: Signup
      parameters:
        - in: "body"
          name: "user"
          description: "用户注册信息"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SignupResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  User:
    type: "object"
    properties:
      phone:
        type: "string"
        description: "手机号"
      password:
        type: "string"
        description: "密码"
      verifycode:
        type: "integer"
        description: "验证码"
  SignupResponse:
    required:
      - errorcode
    properties:
      errorcode:
        type: integer
      errormsg:
        type: string
      data:
        type: object
        properties:
          userid:
            type: integer
          tracenum:
            type: string
            
